### ISSUE TITLE
DB of Bee Library/public checklists

### ISSUE THREAD

**Issue by seltmann** [Big-Bee-Network/Symbiota-light#15]
@GregPost-ASU @mandrewj @egbot can I get a copy of the full Bee Library SQL including all data (not images)? This is for my local version. I want to adjust the menu to include all public checklists listed.

**Comment by seltmann** [comment]
Actually, I think I can do this from the report access you already gave me. Trying now...

**Comment by GregPost-ASU** [comment]
Hi Katja,

Forwarding your request to the Symbiota Support Hub (help@symbiota.org) so that we can track progress there.

Best regards,
Greg
